// Centralized timing constants used across the app.
// Values are milliseconds unless otherwise noted.
export const TIMINGS = {
  TILE_POPULATE_CHECK_INTERVAL: 50,
  TILE_POPULATE_TIMEOUT: 1500,
  TOAST_DISPLAY: 2000,
  LATEST_CONTROL_WEBNOTIF_DELAY: 400,
  LATEST_OVERLAY_QUEUE_DELAY: 1,
  LATEST_OVERLAY_FRAME_BUDGET_MS: 6,
  LATEST_OVERLAY_MIN_CHUNK: 30,
  LOADER_FEATURE_FRAME_BUDGET_MS: 4,
  LOADER_FEATURE_MIN_CHUNK: 1,
};
