const fs = require("fs");
const path = require("path");

const FEATURE_EXPORT_RE = /export\s+const\s+([A-Za-z_$][\w$]*Feature)\s*=/g;

function toPosixPath(value) {
  return String(value || "").replace(/\\/g, "/");
}

function createDuplicateErrorMessage(symbolName, conflicts) {
  return `Duplicate exported feature symbol '${symbolName}' found in ${conflicts.join(" and ")}`;
}

function getEntryPath(entry, rootDir) {
  return toPosixPath(entry.relativePath || path.relative(rootDir, entry.filePath));
}

function findFeatureIndexFiles({ rootDir = process.cwd(), featuresDir = "src/features" } = {}) {
  const absoluteFeaturesDir = path.resolve(rootDir, featuresDir);
  if (!fs.existsSync(absoluteFeaturesDir)) return [];

  return fs
    .readdirSync(absoluteFeaturesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(absoluteFeaturesDir, entry.name, "index.js"))
    .filter((filePath) => fs.existsSync(filePath))
    .sort((left, right) => left.localeCompare(right));
}

function extractFeatureExportsFromSource(source) {
  const exports = [];
  let match;
  while ((match = FEATURE_EXPORT_RE.exec(source))) {
    exports.push(match[1]);
  }
  return exports;
}

function extractFeatureExports(filePath) {
  return extractFeatureExportsFromSource(fs.readFileSync(filePath, "utf8"));
}

function discoverFeatureExportsFromSources(sources, { rootDir = process.cwd() } = {}) {
  return [...sources]
    .sort((left, right) => String(left.filePath).localeCompare(String(right.filePath)))
    .map(({ filePath, source }) => ({
      filePath,
      relativePath: toPosixPath(path.relative(rootDir, filePath)),
      exports: extractFeatureExportsFromSource(source),
    }))
    .filter((entry) => entry.exports.length > 0);
}

function discoverFeatureExports(options = {}) {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const files = findFeatureIndexFiles({ rootDir, featuresDir: options.featuresDir });

  return discoverFeatureExportsFromSources(files.map((filePath) => ({
    filePath,
    source: fs.readFileSync(filePath, "utf8"),
  })), { rootDir });
}

function validateFeatureManifestEntries(entries, { rootDir = process.cwd() } = {}) {
  const errors = [];
  const symbolToPath = new Map();
  const seenPaths = new Set();
  const orderedEntries = [...entries].sort((left, right) =>
    getEntryPath(left, rootDir).localeCompare(getEntryPath(right, rootDir)));

  for (const entry of orderedEntries) {
    const entryPath = getEntryPath(entry, rootDir);
    if (seenPaths.has(entryPath)) errors.push(`Duplicate generated import path '${entryPath}' found in ${entryPath} and ${entryPath}`);
    seenPaths.add(entryPath);

    const symbolsInEntry = new Set();
    for (const symbolName of entry.exports || []) {
      if (symbolsInEntry.has(symbolName)) {
        errors.push(`Duplicate exported feature symbol '${symbolName}' found more than once in ${entryPath}`);
        continue;
      }
      symbolsInEntry.add(symbolName);
      const existingPath = symbolToPath.get(symbolName);
      if (existingPath) errors.push(createDuplicateErrorMessage(symbolName, [existingPath, entryPath]));
      else symbolToPath.set(symbolName, entryPath);
    }
  }

  return [...new Set(errors)].sort((left, right) => left.localeCompare(right));
}

function renderFeatureManifest(entries, { outputFile = "src/generated/features.generated.js" } = {}) {
  const outputDir = toPosixPath(path.dirname(outputFile));
  const imports = [];
  const featureNames = [];

  const orderedEntries = [...entries].sort((left, right) =>
    String(left.relativePath || left.filePath || "").localeCompare(String(right.relativePath || right.filePath || "")));
  orderedEntries.forEach((entry, index) => {
    const names = [...new Set(entry.exports)];
    featureNames.push(...names);
    const importPath = toPosixPath(
      path.relative(outputDir, entry.relativePath).replace(/\.js$/, ".js"),
    );
    const normalizedImportPath = importPath.startsWith(".") ? importPath : `./${importPath}`;
    imports.push(`import { ${names.join(", ")} } from "${normalizedImportPath}";`);
    if (index < orderedEntries.length - 1) imports.push("");
  });

  return [
    "// AUTO-GENERATED by scripts/featureManifest.cjs. Do not edit by hand.",
    ...imports,
    "",
    "export const generatedFeatures = [",
    ...featureNames.map((name) => `  ${name},`),
    "];",
    "",
  ].join("\n");
}

function buildFeatureManifestState(options = {}) {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const outputFile = options.outputFile || "src/generated/features.generated.js";
  const entries = discoverFeatureExports({ ...options, rootDir });
  const errors = validateFeatureManifestEntries(entries, { rootDir });
  const contents = renderFeatureManifest(entries, { outputFile });

  return {
    rootDir,
    outputFile,
    absoluteOutputFile: path.resolve(rootDir, outputFile),
    entries,
    featureNames: entries.flatMap((entry) => entry.exports),
    contents,
    errors,
  };
}

function generateFeatureManifest(options = {}) {
  const state = buildFeatureManifestState(options);
  if (state.errors.length) {
    const details = state.errors.join("\n");
    throw new Error(`Feature manifest generation failed:\n${details}`);
  }

  fs.mkdirSync(path.dirname(state.absoluteOutputFile), { recursive: true });
  fs.writeFileSync(state.absoluteOutputFile, state.contents);

  return {
    outputFile: state.absoluteOutputFile,
    entries: state.entries,
    featureNames: state.featureNames,
    contents: state.contents,
  };
}

function checkFeatureManifest(options = {}) {
  const state = buildFeatureManifestState(options);
  const absoluteOutputFile = path.resolve(state.rootDir, options.outputFile || "src/generated/features.generated.js");
  const actualContent = fs.existsSync(absoluteOutputFile) ? fs.readFileSync(absoluteOutputFile, "utf8") : null;

  return {
    matches: !state.errors.length && actualContent === state.contents,
    actualContent,
    expectedContent: state.contents,
    errors: state.errors,
    outputFile: absoluteOutputFile,
  };
}

module.exports = {
  buildFeatureManifestState,
  checkFeatureManifest,
  discoverFeatureExports,
  discoverFeatureExportsFromSources,
  extractFeatureExports,
  extractFeatureExportsFromSource,
  generateFeatureManifest,
  renderFeatureManifest,
  validateFeatureManifestEntries,
};
