const fs = require("fs");
const path = require("path");

const FEATURE_EXPORT_RE = /export\s+const\s+([A-Za-z_$][\w$]*Feature)\s*=/g;

function toPosixPath(value) {
  return String(value || "").replace(/\\/g, "/");
}

function findFeatureIndexFiles({ rootDir = process.cwd(), featuresDir = "src/features" } = {}) {
  const absoluteFeaturesDir = path.resolve(rootDir, featuresDir);
  if (!fs.existsSync(absoluteFeaturesDir)) return [];

  return fs
    .readdirSync(absoluteFeaturesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(absoluteFeaturesDir, entry.name, "index.js"))
    .filter((filePath) => fs.existsSync(filePath))
    .sort((left, right) => left.localeCompare(right));
}

function extractFeatureExports(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const exports = [];
  let match;
  while ((match = FEATURE_EXPORT_RE.exec(source))) {
    exports.push(match[1]);
  }
  return exports;
}

function discoverFeatureExports(options = {}) {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const files = findFeatureIndexFiles({ rootDir, featuresDir: options.featuresDir });

  return files
    .map((filePath) => ({
      filePath,
      relativePath: toPosixPath(path.relative(rootDir, filePath)),
      exports: extractFeatureExports(filePath),
    }))
    .filter((entry) => entry.exports.length > 0);
}

function renderFeatureManifest(entries, { outputFile = "src/generated/features.generated.js" } = {}) {
  const outputDir = toPosixPath(path.dirname(outputFile));
  const imports = [];
  const featureNames = [];

  entries.forEach((entry, index) => {
    const names = [...new Set(entry.exports)];
    featureNames.push(...names);
    const importPath = toPosixPath(
      path.relative(outputDir, entry.relativePath).replace(/\.js$/, ".js"),
    );
    const normalizedImportPath = importPath.startsWith(".") ? importPath : `./${importPath}`;
    imports.push(`import { ${names.join(", ")} } from "${normalizedImportPath}";`);
    if (index < entries.length - 1) imports.push("");
  });

  return [
    "// AUTO-GENERATED by scripts/featureManifest.cjs. Do not edit by hand.",
    ...imports,
    "",
    "export const generatedFeatures = [",
    ...featureNames.map((name) => `  ${name},`),
    "];",
    "",
  ].join("\n");
}

function generateFeatureManifest(options = {}) {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const outputFile = options.outputFile || "src/generated/features.generated.js";
  const entries = discoverFeatureExports({ ...options, rootDir });
  const contents = renderFeatureManifest(entries, { outputFile });
  const absoluteOutputFile = path.resolve(rootDir, outputFile);

  fs.mkdirSync(path.dirname(absoluteOutputFile), { recursive: true });
  fs.writeFileSync(absoluteOutputFile, contents);

  return {
    outputFile: absoluteOutputFile,
    entries,
    featureNames: entries.flatMap((entry) => entry.exports),
    contents,
  };
}

module.exports = {
  discoverFeatureExports,
  extractFeatureExports,
  generateFeatureManifest,
  renderFeatureManifest,
};
