const fs = require("fs");
const path = require("path");

const FEATURE_EXPORT_RE = /export\s+const\s+([A-Za-z_$][\w$]*Feature)\s*=/g;

function toPosixPath(value) {
  return String(value || "").replace(/\\/g, "/");
}

function createDuplicateErrorMessage(symbolName, conflicts) {
  return `Duplicate exported feature symbol '${symbolName}' found in ${conflicts.join(" and ")}`;
}

function findFeatureIndexFiles({ rootDir = process.cwd(), featuresDir = "src/features" } = {}) {
  const absoluteFeaturesDir = path.resolve(rootDir, featuresDir);
  if (!fs.existsSync(absoluteFeaturesDir)) return [];

  return fs
    .readdirSync(absoluteFeaturesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => path.join(absoluteFeaturesDir, entry.name, "index.js"))
    .filter((filePath) => fs.existsSync(filePath))
    .sort((left, right) => left.localeCompare(right));
}

function extractFeatureExports(filePath) {
  const source = fs.readFileSync(filePath, "utf8");
  const exports = [];
  let match;
  while ((match = FEATURE_EXPORT_RE.exec(source))) {
    exports.push(match[1]);
  }
  return exports;
}

function discoverFeatureExports(options = {}) {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const files = findFeatureIndexFiles({ rootDir, featuresDir: options.featuresDir });

  return files
    .map((filePath) => ({
      filePath,
      relativePath: toPosixPath(path.relative(rootDir, filePath)),
      exports: extractFeatureExports(filePath),
    }))
    .filter((entry) => entry.exports.length > 0);
}

function validateFeatureManifestEntries(entries, { rootDir = process.cwd() } = {}) {
  const errors = [];
  const symbolToPaths = new Map();
  const pathToSymbols = new Map();

  entries.forEach((entry) => {
    const normalizedPath = toPosixPath(path.relative(rootDir, entry.filePath));
    entry.exports.forEach((symbolName) => {
      const existingPaths = symbolToPaths.get(symbolName);
      if (existingPaths) {
        errors.push(createDuplicateErrorMessage(symbolName, [existingPaths[0], normalizedPath]));
        return;
      }
      symbolToPaths.set(symbolName, [normalizedPath]);
    });

    const entryPath = toPosixPath(path.relative(rootDir, entry.filePath));
    const existingSymbols = pathToSymbols.get(entryPath);
    if (existingSymbols) {
      errors.push(`Duplicate feature export list for ${entryPath}`);
      return;
    }
    pathToSymbols.set(entryPath, entry.exports);
  });

  return errors;
}

function renderFeatureManifest(entries, { outputFile = "src/generated/features.generated.js" } = {}) {
  const outputDir = toPosixPath(path.dirname(outputFile));
  const imports = [];
  const featureNames = [];

  entries.forEach((entry, index) => {
    const names = [...new Set(entry.exports)];
    featureNames.push(...names);
    const importPath = toPosixPath(
      path.relative(outputDir, entry.relativePath).replace(/\.js$/, ".js"),
    );
    const normalizedImportPath = importPath.startsWith(".") ? importPath : `./${importPath}`;
    imports.push(`import { ${names.join(", ")} } from "${normalizedImportPath}";`);
    if (index < entries.length - 1) imports.push("");
  });

  return [
    "// AUTO-GENERATED by scripts/featureManifest.cjs. Do not edit by hand.",
    ...imports,
    "",
    "export const generatedFeatures = [",
    ...featureNames.map((name) => `  ${name},`),
    "];",
    "",
  ].join("\n");
}

function buildFeatureManifestState(options = {}) {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const outputFile = options.outputFile || "src/generated/features.generated.js";
  const entries = discoverFeatureExports({ ...options, rootDir });
  const errors = validateFeatureManifestEntries(entries, { rootDir });
  const contents = renderFeatureManifest(entries, { outputFile });

  return {
    rootDir,
    outputFile,
    absoluteOutputFile: path.resolve(rootDir, outputFile),
    entries,
    featureNames: entries.flatMap((entry) => entry.exports),
    contents,
    errors,
  };
}

function generateFeatureManifest(options = {}) {
  const state = buildFeatureManifestState(options);
  if (state.errors.length) {
    const details = state.errors.join("\n");
    throw new Error(`Feature manifest generation failed:\n${details}`);
  }

  fs.mkdirSync(path.dirname(state.absoluteOutputFile), { recursive: true });
  fs.writeFileSync(state.absoluteOutputFile, state.contents);

  return {
    outputFile: state.absoluteOutputFile,
    entries: state.entries,
    featureNames: state.featureNames,
    contents: state.contents,
  };
}

function checkFeatureManifest(options = {}) {
  const state = buildFeatureManifestState(options);
  const absoluteOutputFile = path.resolve(state.rootDir, options.outputFile || "src/generated/features.generated.js");
  const actualContent = fs.existsSync(absoluteOutputFile) ? fs.readFileSync(absoluteOutputFile, "utf8") : null;

  return {
    matches: !state.errors.length && actualContent === state.contents,
    actualContent,
    expectedContent: state.contents,
    errors: state.errors,
    outputFile: absoluteOutputFile,
  };
}

module.exports = {
  buildFeatureManifestState,
  checkFeatureManifest,
  discoverFeatureExports,
  extractFeatureExports,
  generateFeatureManifest,
  renderFeatureManifest,
  validateFeatureManifestEntries,
};
